name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - name: Upload diff output
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: diff-output
          path: src/__tests__/__image_snapshots__/__diff_output__/
