name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - name: Upload diff output
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: diff-output
          path: src/__tests__/__image_snapshots__/__diff_output__/
